version: '3.8'

services:
    mariadb:
        image: mariadb:11.2.2
        container_name: demo-ts-fp-mariadb-local
        ports:
            - '3307:3306'
        environment:
            MARIADB_ROOT_PASSWORD: mariadb
            MARIADB_DATABASE: demo_db
            MARIADB_USER: demo_user
            MARIADB_PASSWORD: demo_mariadb
        volumes:
            - demo-ts-fp-mariadb-local-data:/var/lib/mysql

volumes:
    demo-ts-fp-mariadb-local-data:
